// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.28.2
// source: api/room_service/room_service.proto

package room_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// --------------------- universal types
type DateEditMode int32

const (
	DateEditMode_SET    DateEditMode = 0
	DateEditMode_DELETE DateEditMode = 1
	DateEditMode_APPEND DateEditMode = 2 // for list or map
)

// Enum value maps for DateEditMode.
var (
	DateEditMode_name = map[int32]string{
		0: "SET",
		1: "DELETE",
		2: "APPEND",
	}
	DateEditMode_value = map[string]int32{
		"SET":    0,
		"DELETE": 1,
		"APPEND": 2,
	}
)

func (x DateEditMode) Enum() *DateEditMode {
	p := new(DateEditMode)
	*p = x
	return p
}

func (x DateEditMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DateEditMode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_room_service_room_service_proto_enumTypes[0].Descriptor()
}

func (DateEditMode) Type() protoreflect.EnumType {
	return &file_api_room_service_room_service_proto_enumTypes[0]
}

func (x DateEditMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DateEditMode.Descriptor instead.
func (DateEditMode) EnumDescriptor() ([]byte, []int) {
	return file_api_room_service_room_service_proto_rawDescGZIP(), []int{0}
}

type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*Value_StringValue
	//	*Value_IntValue
	//	*Value_FloatValue
	//	*Value_BoolValue
	//	*Value_BinaryValue
	//	*Value_ListValue
	//	*Value_MapValue
	Value         isValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_api_room_service_room_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_api_room_service_room_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_api_room_service_room_service_proto_rawDescGZIP(), []int{0}
}

func (x *Value) GetValue() isValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Value) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*Value_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Value) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*Value_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *Value) GetFloatValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*Value_FloatValue); ok {
			return x.FloatValue
		}
	}
	return 0
}

func (x *Value) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*Value_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *Value) GetBinaryValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*Value_BinaryValue); ok {
			return x.BinaryValue
		}
	}
	return nil
}

func (x *Value) GetListValue() *ListValue {
	if x != nil {
		if x, ok := x.Value.(*Value_ListValue); ok {
			return x.ListValue
		}
	}
	return nil
}

func (x *Value) GetMapValue() *MapValue {
	if x != nil {
		if x, ok := x.Value.(*Value_MapValue); ok {
			return x.MapValue
		}
	}
	return nil
}

type isValue_Value interface {
	isValue_Value()
}

type Value_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Value_IntValue struct {
	IntValue int64 `protobuf:"varint,2,opt,name=int_value,json=intValue,proto3,oneof"`
}

type Value_FloatValue struct {
	FloatValue float64 `protobuf:"fixed64,3,opt,name=float_value,json=floatValue,proto3,oneof"`
}

type Value_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type Value_BinaryValue struct {
	BinaryValue []byte `protobuf:"bytes,5,opt,name=binary_value,json=binaryValue,proto3,oneof"`
}

type Value_ListValue struct {
	ListValue *ListValue `protobuf:"bytes,6,opt,name=list_value,json=listValue,proto3,oneof"`
}

type Value_MapValue struct {
	MapValue *MapValue `protobuf:"bytes,7,opt,name=map_value,json=mapValue,proto3,oneof"`
}

func (*Value_StringValue) isValue_Value() {}

func (*Value_IntValue) isValue_Value() {}

func (*Value_FloatValue) isValue_Value() {}

func (*Value_BoolValue) isValue_Value() {}

func (*Value_BinaryValue) isValue_Value() {}

func (*Value_ListValue) isValue_Value() {}

func (*Value_MapValue) isValue_Value() {}

// custom types for Value
type ListValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*Value               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListValue) Reset() {
	*x = ListValue{}
	mi := &file_api_room_service_room_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListValue) ProtoMessage() {}

func (x *ListValue) ProtoReflect() protoreflect.Message {
	mi := &file_api_room_service_room_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListValue.ProtoReflect.Descriptor instead.
func (*ListValue) Descriptor() ([]byte, []int) {
	return file_api_room_service_room_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListValue) GetValues() []*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

type MapValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        map[string]*Value      `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapValue) Reset() {
	*x = MapValue{}
	mi := &file_api_room_service_room_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapValue) ProtoMessage() {}

func (x *MapValue) ProtoReflect() protoreflect.Message {
	mi := &file_api_room_service_room_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapValue.ProtoReflect.Descriptor instead.
func (*MapValue) Descriptor() ([]byte, []int) {
	return file_api_room_service_room_service_proto_rawDescGZIP(), []int{2}
}

func (x *MapValue) GetValues() map[string]*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // what if client wants to store some data e.g. avatar id
	JoinedAt      int64                  `protobuf:"varint,4,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_api_room_service_room_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_api_room_service_room_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_api_room_service_room_service_proto_rawDescGZIP(), []int{3}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *User) GetJoinedAt() int64 {
	if x != nil {
		return x.JoinedAt
	}
	return 0
}

type RoomData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        map[string]*Value      `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // users are displayed as list in snapshot, not a field of RoomData
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomData) Reset() {
	*x = RoomData{}
	mi := &file_api_room_service_room_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomData) ProtoMessage() {}

func (x *RoomData) ProtoReflect() protoreflect.Message {
	mi := &file_api_room_service_room_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomData.ProtoReflect.Descriptor instead.
func (*RoomData) Descriptor() ([]byte, []int) {
	return file_api_room_service_room_service_proto_rawDescGZIP(), []int{4}
}

func (x *RoomData) GetValues() map[string]*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

type Command struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CommandId string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"` // no-repeat
	Timestamp int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	RoomId    string                 `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId    string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Command_CreateRoom
	//	*Command_DeleteRoom
	//	*Command_JoinRoom
	//	*Command_LeaveRoom
	//	*Command_AffectData
	//	*Command_RefreshRoom
	Payload       isCommand_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_api_room_service_room_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_api_room_service_room_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_api_room_service_room_service_proto_rawDescGZIP(), []int{5}
}

func (x *Command) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *Command) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Command) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *Command) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Command) GetPayload() isCommand_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Command) GetCreateRoom() *CreateRoomCommandBody {
	if x != nil {
		if x, ok := x.Payload.(*Command_CreateRoom); ok {
			return x.CreateRoom
		}
	}
	return nil
}

func (x *Command) GetDeleteRoom() *DeleteRoomCommandBody {
	if x != nil {
		if x, ok := x.Payload.(*Command_DeleteRoom); ok {
			return x.DeleteRoom
		}
	}
	return nil
}

func (x *Command) GetJoinRoom() *JoinRoomCommandBody {
	if x != nil {
		if x, ok := x.Payload.(*Command_JoinRoom); ok {
			return x.JoinRoom
		}
	}
	return nil
}

func (x *Command) GetLeaveRoom() *LeaveRoomCommandBody {
	if x != nil {
		if x, ok := x.Payload.(*Command_LeaveRoom); ok {
			return x.LeaveRoom
		}
	}
	return nil
}

func (x *Command) GetAffectData() *SetAppendDeleteDataCommandBody {
	if x != nil {
		if x, ok := x.Payload.(*Command_AffectData); ok {
			return x.AffectData
		}
	}
	return nil
}

func (x *Command) GetRefreshRoom() *RefreshRoomCommandBody {
	if x != nil {
		if x, ok := x.Payload.(*Command_RefreshRoom); ok {
			return x.RefreshRoom
		}
	}
	return nil
}

type isCommand_Payload interface {
	isCommand_Payload()
}

type Command_CreateRoom struct {
	CreateRoom *CreateRoomCommandBody `protobuf:"bytes,10,opt,name=create_room,json=createRoom,proto3,oneof"`
}

type Command_DeleteRoom struct {
	DeleteRoom *DeleteRoomCommandBody `protobuf:"bytes,11,opt,name=delete_room,json=deleteRoom,proto3,oneof"`
}

type Command_JoinRoom struct {
	JoinRoom *JoinRoomCommandBody `protobuf:"bytes,20,opt,name=join_room,json=joinRoom,proto3,oneof"`
}

type Command_LeaveRoom struct {
	LeaveRoom *LeaveRoomCommandBody `protobuf:"bytes,21,opt,name=leave_room,json=leaveRoom,proto3,oneof"`
}

type Command_AffectData struct {
	AffectData *SetAppendDeleteDataCommandBody `protobuf:"bytes,30,opt,name=affect_data,json=affectData,proto3,oneof"` // create, update, delete
}

type Command_RefreshRoom struct {
	RefreshRoom *RefreshRoomCommandBody `protobuf:"bytes,40,opt,name=refresh_room,json=refreshRoom,proto3,oneof"`
}

func (*Command_CreateRoom) isCommand_Payload() {}

func (*Command_DeleteRoom) isCommand_Payload() {}

func (*Command_JoinRoom) isCommand_Payload() {}

func (*Command_LeaveRoom) isCommand_Payload() {}

func (*Command_AffectData) isCommand_Payload() {}

func (*Command_RefreshRoom) isCommand_Payload() {}

// bodies of command: can't be used on their own
type CreateRoomCommandBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomOptions   map[string]string      `protobuf:"bytes,1,rep,name=room_options,json=roomOptions,proto3" json:"room_options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // max_users for example
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomCommandBody) Reset() {
	*x = CreateRoomCommandBody{}
	mi := &file_api_room_service_room_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomCommandBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomCommandBody) ProtoMessage() {}

func (x *CreateRoomCommandBody) ProtoReflect() protoreflect.Message {
	mi := &file_api_room_service_room_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomCommandBody.ProtoReflect.Descriptor instead.
func (*CreateRoomCommandBody) Descriptor() ([]byte, []int) {
	return file_api_room_service_room_service_proto_rawDescGZIP(), []int{6}
}

func (x *CreateRoomCommandBody) GetRoomOptions() map[string]string {
	if x != nil {
		return x.RoomOptions
	}
	return nil
}

type DeleteRoomCommandBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeleteApprove bool                   `protobuf:"varint,1,opt,name=delete_approve,json=deleteApprove,proto3" json:"delete_approve,omitempty"` // to differ from LeaveRoomCommandBody as it's empty too
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoomCommandBody) Reset() {
	*x = DeleteRoomCommandBody{}
	mi := &file_api_room_service_room_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoomCommandBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoomCommandBody) ProtoMessage() {}

func (x *DeleteRoomCommandBody) ProtoReflect() protoreflect.Message {
	mi := &file_api_room_service_room_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoomCommandBody.ProtoReflect.Descriptor instead.
func (*DeleteRoomCommandBody) Descriptor() ([]byte, []int) {
	return file_api_room_service_room_service_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteRoomCommandBody) GetDeleteApprove() bool {
	if x != nil {
		return x.DeleteApprove
	}
	return false
}

type JoinRoomCommandBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserFull      *User                  `protobuf:"bytes,1,opt,name=user_full,json=userFull,proto3" json:"user_full,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomCommandBody) Reset() {
	*x = JoinRoomCommandBody{}
	mi := &file_api_room_service_room_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomCommandBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomCommandBody) ProtoMessage() {}

func (x *JoinRoomCommandBody) ProtoReflect() protoreflect.Message {
	mi := &file_api_room_service_room_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomCommandBody.ProtoReflect.Descriptor instead.
func (*JoinRoomCommandBody) Descriptor() ([]byte, []int) {
	return file_api_room_service_room_service_proto_rawDescGZIP(), []int{8}
}

func (x *JoinRoomCommandBody) GetUserFull() *User {
	if x != nil {
		return x.UserFull
	}
	return nil
}

type LeaveRoomCommandBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaveApprove  bool                   `protobuf:"varint,1,opt,name=leave_approve,json=leaveApprove,proto3" json:"leave_approve,omitempty"` // to differ from DeleteRoomCommandBody as it's empty too
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoomCommandBody) Reset() {
	*x = LeaveRoomCommandBody{}
	mi := &file_api_room_service_room_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoomCommandBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoomCommandBody) ProtoMessage() {}

func (x *LeaveRoomCommandBody) ProtoReflect() protoreflect.Message {
	mi := &file_api_room_service_room_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoomCommandBody.ProtoReflect.Descriptor instead.
func (*LeaveRoomCommandBody) Descriptor() ([]byte, []int) {
	return file_api_room_service_room_service_proto_rawDescGZIP(), []int{9}
}

func (x *LeaveRoomCommandBody) GetLeaveApprove() bool {
	if x != nil {
		return x.LeaveApprove
	}
	return false
}

type SetAppendDeleteDataCommandBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataId        string                 `protobuf:"bytes,1,opt,name=data_id,json=dataId,proto3" json:"data_id,omitempty"`
	DataValue     *Value                 `protobuf:"bytes,2,opt,name=data_value,json=dataValue,proto3,oneof" json:"data_value,omitempty"` // no need for delete
	CommandMode   DateEditMode           `protobuf:"varint,3,opt,name=command_mode,json=commandMode,proto3,enum=api.DateEditMode" json:"command_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAppendDeleteDataCommandBody) Reset() {
	*x = SetAppendDeleteDataCommandBody{}
	mi := &file_api_room_service_room_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAppendDeleteDataCommandBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAppendDeleteDataCommandBody) ProtoMessage() {}

func (x *SetAppendDeleteDataCommandBody) ProtoReflect() protoreflect.Message {
	mi := &file_api_room_service_room_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAppendDeleteDataCommandBody.ProtoReflect.Descriptor instead.
func (*SetAppendDeleteDataCommandBody) Descriptor() ([]byte, []int) {
	return file_api_room_service_room_service_proto_rawDescGZIP(), []int{10}
}

func (x *SetAppendDeleteDataCommandBody) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

func (x *SetAppendDeleteDataCommandBody) GetDataValue() *Value {
	if x != nil {
		return x.DataValue
	}
	return nil
}

func (x *SetAppendDeleteDataCommandBody) GetCommandMode() DateEditMode {
	if x != nil {
		return x.CommandMode
	}
	return DateEditMode_SET
}

type RefreshRoomCommandBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshRoom   bool                   `protobuf:"varint,1,opt,name=refresh_room,json=refreshRoom,proto3" json:"refresh_room,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshRoomCommandBody) Reset() {
	*x = RefreshRoomCommandBody{}
	mi := &file_api_room_service_room_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRoomCommandBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRoomCommandBody) ProtoMessage() {}

func (x *RefreshRoomCommandBody) ProtoReflect() protoreflect.Message {
	mi := &file_api_room_service_room_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRoomCommandBody.ProtoReflect.Descriptor instead.
func (*RefreshRoomCommandBody) Descriptor() ([]byte, []int) {
	return file_api_room_service_room_service_proto_rawDescGZIP(), []int{11}
}

func (x *RefreshRoomCommandBody) GetRefreshRoom() bool {
	if x != nil {
		return x.RefreshRoom
	}
	return false
}

type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// string event_id = 1;
	Timestamp int64  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	RoomId    string `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	UserId    string `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Event_RoomCreated
	//	*Event_RoomDeleted
	//	*Event_JoinedRoom
	//	*Event_LeftRoom
	//	*Event_DataEdited
	//	*Event_FullRoom
	Payload       isEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_api_room_service_room_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_api_room_service_room_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_api_room_service_room_service_proto_rawDescGZIP(), []int{12}
}

func (x *Event) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Event) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *Event) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Event) GetPayload() isEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetRoomCreated() *RoomCreatedEventBody {
	if x != nil {
		if x, ok := x.Payload.(*Event_RoomCreated); ok {
			return x.RoomCreated
		}
	}
	return nil
}

func (x *Event) GetRoomDeleted() *RoomDeletedEventBody {
	if x != nil {
		if x, ok := x.Payload.(*Event_RoomDeleted); ok {
			return x.RoomDeleted
		}
	}
	return nil
}

func (x *Event) GetJoinedRoom() *JoinedRoomEventBody {
	if x != nil {
		if x, ok := x.Payload.(*Event_JoinedRoom); ok {
			return x.JoinedRoom
		}
	}
	return nil
}

func (x *Event) GetLeftRoom() *LeftRoomEventBody {
	if x != nil {
		if x, ok := x.Payload.(*Event_LeftRoom); ok {
			return x.LeftRoom
		}
	}
	return nil
}

func (x *Event) GetDataEdited() *DataEditedEventBody {
	if x != nil {
		if x, ok := x.Payload.(*Event_DataEdited); ok {
			return x.DataEdited
		}
	}
	return nil
}

func (x *Event) GetFullRoom() *FullRoomSnapshotEventBody {
	if x != nil {
		if x, ok := x.Payload.(*Event_FullRoom); ok {
			return x.FullRoom
		}
	}
	return nil
}

type isEvent_Payload interface {
	isEvent_Payload()
}

type Event_RoomCreated struct {
	RoomCreated *RoomCreatedEventBody `protobuf:"bytes,10,opt,name=room_created,json=roomCreated,proto3,oneof"`
}

type Event_RoomDeleted struct {
	RoomDeleted *RoomDeletedEventBody `protobuf:"bytes,11,opt,name=room_deleted,json=roomDeleted,proto3,oneof"`
}

type Event_JoinedRoom struct {
	JoinedRoom *JoinedRoomEventBody `protobuf:"bytes,20,opt,name=joined_room,json=joinedRoom,proto3,oneof"`
}

type Event_LeftRoom struct {
	LeftRoom *LeftRoomEventBody `protobuf:"bytes,21,opt,name=left_room,json=leftRoom,proto3,oneof"`
}

type Event_DataEdited struct {
	DataEdited *DataEditedEventBody `protobuf:"bytes,30,opt,name=data_edited,json=dataEdited,proto3,oneof"`
}

type Event_FullRoom struct {
	FullRoom *FullRoomSnapshotEventBody `protobuf:"bytes,40,opt,name=full_room,json=fullRoom,proto3,oneof"`
}

func (*Event_RoomCreated) isEvent_Payload() {}

func (*Event_RoomDeleted) isEvent_Payload() {}

func (*Event_JoinedRoom) isEvent_Payload() {}

func (*Event_LeftRoom) isEvent_Payload() {}

func (*Event_DataEdited) isEvent_Payload() {}

func (*Event_FullRoom) isEvent_Payload() {}

// bodies of event: can't be used on their own
type RoomCreatedEventBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomOptions   map[string]string      `protobuf:"bytes,1,rep,name=room_options,json=roomOptions,proto3" json:"room_options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // max_users for example
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomCreatedEventBody) Reset() {
	*x = RoomCreatedEventBody{}
	mi := &file_api_room_service_room_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomCreatedEventBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomCreatedEventBody) ProtoMessage() {}

func (x *RoomCreatedEventBody) ProtoReflect() protoreflect.Message {
	mi := &file_api_room_service_room_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomCreatedEventBody.ProtoReflect.Descriptor instead.
func (*RoomCreatedEventBody) Descriptor() ([]byte, []int) {
	return file_api_room_service_room_service_proto_rawDescGZIP(), []int{13}
}

func (x *RoomCreatedEventBody) GetRoomOptions() map[string]string {
	if x != nil {
		return x.RoomOptions
	}
	return nil
}

type RoomDeletedEventBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomDeleted   bool                   `protobuf:"varint,1,opt,name=room_deleted,json=roomDeleted,proto3" json:"room_deleted,omitempty"` // to differ from LeftRoomEventBody as it's empty too
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomDeletedEventBody) Reset() {
	*x = RoomDeletedEventBody{}
	mi := &file_api_room_service_room_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomDeletedEventBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomDeletedEventBody) ProtoMessage() {}

func (x *RoomDeletedEventBody) ProtoReflect() protoreflect.Message {
	mi := &file_api_room_service_room_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomDeletedEventBody.ProtoReflect.Descriptor instead.
func (*RoomDeletedEventBody) Descriptor() ([]byte, []int) {
	return file_api_room_service_room_service_proto_rawDescGZIP(), []int{14}
}

func (x *RoomDeletedEventBody) GetRoomDeleted() bool {
	if x != nil {
		return x.RoomDeleted
	}
	return false
}

type JoinedRoomEventBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserFull      *User                  `protobuf:"bytes,1,opt,name=user_full,json=userFull,proto3" json:"user_full,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinedRoomEventBody) Reset() {
	*x = JoinedRoomEventBody{}
	mi := &file_api_room_service_room_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinedRoomEventBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinedRoomEventBody) ProtoMessage() {}

func (x *JoinedRoomEventBody) ProtoReflect() protoreflect.Message {
	mi := &file_api_room_service_room_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinedRoomEventBody.ProtoReflect.Descriptor instead.
func (*JoinedRoomEventBody) Descriptor() ([]byte, []int) {
	return file_api_room_service_room_service_proto_rawDescGZIP(), []int{15}
}

func (x *JoinedRoomEventBody) GetUserFull() *User {
	if x != nil {
		return x.UserFull
	}
	return nil
}

type LeftRoomEventBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeftRoom      bool                   `protobuf:"varint,1,opt,name=left_room,json=leftRoom,proto3" json:"left_room,omitempty"` // to differ from RoomDeletedEventBody as it's empty too
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeftRoomEventBody) Reset() {
	*x = LeftRoomEventBody{}
	mi := &file_api_room_service_room_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeftRoomEventBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeftRoomEventBody) ProtoMessage() {}

func (x *LeftRoomEventBody) ProtoReflect() protoreflect.Message {
	mi := &file_api_room_service_room_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeftRoomEventBody.ProtoReflect.Descriptor instead.
func (*LeftRoomEventBody) Descriptor() ([]byte, []int) {
	return file_api_room_service_room_service_proto_rawDescGZIP(), []int{16}
}

func (x *LeftRoomEventBody) GetLeftRoom() bool {
	if x != nil {
		return x.LeftRoom
	}
	return false
}

// data edited can be created, edited & deleted
type DataEditedEventBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataId        string                 `protobuf:"bytes,1,opt,name=data_id,json=dataId,proto3" json:"data_id,omitempty"`
	DataValue     *Value                 `protobuf:"bytes,2,opt,name=data_value,json=dataValue,proto3,oneof" json:"data_value,omitempty"` // no need for delete
	CommandMode   DateEditMode           `protobuf:"varint,3,opt,name=command_mode,json=commandMode,proto3,enum=api.DateEditMode" json:"command_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataEditedEventBody) Reset() {
	*x = DataEditedEventBody{}
	mi := &file_api_room_service_room_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataEditedEventBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataEditedEventBody) ProtoMessage() {}

func (x *DataEditedEventBody) ProtoReflect() protoreflect.Message {
	mi := &file_api_room_service_room_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataEditedEventBody.ProtoReflect.Descriptor instead.
func (*DataEditedEventBody) Descriptor() ([]byte, []int) {
	return file_api_room_service_room_service_proto_rawDescGZIP(), []int{17}
}

func (x *DataEditedEventBody) GetDataId() string {
	if x != nil {
		return x.DataId
	}
	return ""
}

func (x *DataEditedEventBody) GetDataValue() *Value {
	if x != nil {
		return x.DataValue
	}
	return nil
}

func (x *DataEditedEventBody) GetCommandMode() DateEditMode {
	if x != nil {
		return x.CommandMode
	}
	return DateEditMode_SET
}

type FullRoomSnapshotEventBody struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Room          *RoomData              `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	Users         []*User                `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FullRoomSnapshotEventBody) Reset() {
	*x = FullRoomSnapshotEventBody{}
	mi := &file_api_room_service_room_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FullRoomSnapshotEventBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FullRoomSnapshotEventBody) ProtoMessage() {}

func (x *FullRoomSnapshotEventBody) ProtoReflect() protoreflect.Message {
	mi := &file_api_room_service_room_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FullRoomSnapshotEventBody.ProtoReflect.Descriptor instead.
func (*FullRoomSnapshotEventBody) Descriptor() ([]byte, []int) {
	return file_api_room_service_room_service_proto_rawDescGZIP(), []int{18}
}

func (x *FullRoomSnapshotEventBody) GetRoom() *RoomData {
	if x != nil {
		return x.Room
	}
	return nil
}

func (x *FullRoomSnapshotEventBody) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type SingleEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*SingleEvent_FullRoom
	//	*SingleEvent_RoomDeleted
	Result        isSingleEvent_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SingleEvent) Reset() {
	*x = SingleEvent{}
	mi := &file_api_room_service_room_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingleEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleEvent) ProtoMessage() {}

func (x *SingleEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_room_service_room_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleEvent.ProtoReflect.Descriptor instead.
func (*SingleEvent) Descriptor() ([]byte, []int) {
	return file_api_room_service_room_service_proto_rawDescGZIP(), []int{19}
}

func (x *SingleEvent) GetResult() isSingleEvent_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *SingleEvent) GetFullRoom() *FullRoomSnapshotEventBody {
	if x != nil {
		if x, ok := x.Result.(*SingleEvent_FullRoom); ok {
			return x.FullRoom
		}
	}
	return nil
}

func (x *SingleEvent) GetRoomDeleted() *RoomDeletedEventBody {
	if x != nil {
		if x, ok := x.Result.(*SingleEvent_RoomDeleted); ok {
			return x.RoomDeleted
		}
	}
	return nil
}

type isSingleEvent_Result interface {
	isSingleEvent_Result()
}

type SingleEvent_FullRoom struct {
	FullRoom *FullRoomSnapshotEventBody `protobuf:"bytes,1,opt,name=full_room,json=fullRoom,proto3,oneof"`
}

type SingleEvent_RoomDeleted struct {
	RoomDeleted *RoomDeletedEventBody `protobuf:"bytes,2,opt,name=room_deleted,json=roomDeleted,proto3,oneof"`
}

func (*SingleEvent_FullRoom) isSingleEvent_Result() {}

func (*SingleEvent_RoomDeleted) isSingleEvent_Result() {}

var File_api_room_service_room_service_proto protoreflect.FileDescriptor

const file_api_room_service_room_service_proto_rawDesc = "" +
	"\n" +
	"#api/room_service/room_service.proto\x12\x03api\"\x9c\x02\n" +
	"\x05Value\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12\x1d\n" +
	"\tint_value\x18\x02 \x01(\x03H\x00R\bintValue\x12!\n" +
	"\vfloat_value\x18\x03 \x01(\x01H\x00R\n" +
	"floatValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x04 \x01(\bH\x00R\tboolValue\x12#\n" +
	"\fbinary_value\x18\x05 \x01(\fH\x00R\vbinaryValue\x12/\n" +
	"\n" +
	"list_value\x18\x06 \x01(\v2\x0e.api.ListValueH\x00R\tlistValue\x12,\n" +
	"\tmap_value\x18\a \x01(\v2\r.api.MapValueH\x00R\bmapValueB\a\n" +
	"\x05value\"/\n" +
	"\tListValue\x12\"\n" +
	"\x06values\x18\x01 \x03(\v2\n" +
	".api.ValueR\x06values\"\x84\x01\n" +
	"\bMapValue\x121\n" +
	"\x06values\x18\x01 \x03(\v2\x19.api.MapValue.ValuesEntryR\x06values\x1aE\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12 \n" +
	"\x05value\x18\x02 \x01(\v2\n" +
	".api.ValueR\x05value:\x028\x01\"\xb9\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x123\n" +
	"\bmetadata\x18\x03 \x03(\v2\x17.api.User.MetadataEntryR\bmetadata\x12\x1b\n" +
	"\tjoined_at\x18\x04 \x01(\x03R\bjoinedAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x84\x01\n" +
	"\bRoomData\x121\n" +
	"\x06values\x18\x01 \x03(\v2\x19.api.RoomData.ValuesEntryR\x06values\x1aE\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12 \n" +
	"\x05value\x18\x02 \x01(\v2\n" +
	".api.ValueR\x05value:\x028\x01\"\x80\x04\n" +
	"\aCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12=\n" +
	"\vcreate_room\x18\n" +
	" \x01(\v2\x1a.api.CreateRoomCommandBodyH\x00R\n" +
	"createRoom\x12=\n" +
	"\vdelete_room\x18\v \x01(\v2\x1a.api.DeleteRoomCommandBodyH\x00R\n" +
	"deleteRoom\x127\n" +
	"\tjoin_room\x18\x14 \x01(\v2\x18.api.JoinRoomCommandBodyH\x00R\bjoinRoom\x12:\n" +
	"\n" +
	"leave_room\x18\x15 \x01(\v2\x19.api.LeaveRoomCommandBodyH\x00R\tleaveRoom\x12F\n" +
	"\vaffect_data\x18\x1e \x01(\v2#.api.SetAppendDeleteDataCommandBodyH\x00R\n" +
	"affectData\x12@\n" +
	"\frefresh_room\x18( \x01(\v2\x1b.api.RefreshRoomCommandBodyH\x00R\vrefreshRoomB\t\n" +
	"\apayload\"\xa7\x01\n" +
	"\x15CreateRoomCommandBody\x12N\n" +
	"\froom_options\x18\x01 \x03(\v2+.api.CreateRoomCommandBody.RoomOptionsEntryR\vroomOptions\x1a>\n" +
	"\x10RoomOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\">\n" +
	"\x15DeleteRoomCommandBody\x12%\n" +
	"\x0edelete_approve\x18\x01 \x01(\bR\rdeleteApprove\"=\n" +
	"\x13JoinRoomCommandBody\x12&\n" +
	"\tuser_full\x18\x01 \x01(\v2\t.api.UserR\buserFull\";\n" +
	"\x14LeaveRoomCommandBody\x12#\n" +
	"\rleave_approve\x18\x01 \x01(\bR\fleaveApprove\"\xae\x01\n" +
	"\x1eSetAppendDeleteDataCommandBody\x12\x17\n" +
	"\adata_id\x18\x01 \x01(\tR\x06dataId\x12.\n" +
	"\n" +
	"data_value\x18\x02 \x01(\v2\n" +
	".api.ValueH\x00R\tdataValue\x88\x01\x01\x124\n" +
	"\fcommand_mode\x18\x03 \x01(\x0e2\x11.api.DateEditModeR\vcommandModeB\r\n" +
	"\v_data_value\";\n" +
	"\x16RefreshRoomCommandBody\x12!\n" +
	"\frefresh_room\x18\x01 \x01(\bR\vrefreshRoom\"\xd2\x03\n" +
	"\x05Event\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\tR\x06roomId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12>\n" +
	"\froom_created\x18\n" +
	" \x01(\v2\x19.api.RoomCreatedEventBodyH\x00R\vroomCreated\x12>\n" +
	"\froom_deleted\x18\v \x01(\v2\x19.api.RoomDeletedEventBodyH\x00R\vroomDeleted\x12;\n" +
	"\vjoined_room\x18\x14 \x01(\v2\x18.api.JoinedRoomEventBodyH\x00R\n" +
	"joinedRoom\x125\n" +
	"\tleft_room\x18\x15 \x01(\v2\x16.api.LeftRoomEventBodyH\x00R\bleftRoom\x12;\n" +
	"\vdata_edited\x18\x1e \x01(\v2\x18.api.DataEditedEventBodyH\x00R\n" +
	"dataEdited\x12=\n" +
	"\tfull_room\x18( \x01(\v2\x1e.api.FullRoomSnapshotEventBodyH\x00R\bfullRoomB\t\n" +
	"\apayload\"\xa5\x01\n" +
	"\x14RoomCreatedEventBody\x12M\n" +
	"\froom_options\x18\x01 \x03(\v2*.api.RoomCreatedEventBody.RoomOptionsEntryR\vroomOptions\x1a>\n" +
	"\x10RoomOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"9\n" +
	"\x14RoomDeletedEventBody\x12!\n" +
	"\froom_deleted\x18\x01 \x01(\bR\vroomDeleted\"=\n" +
	"\x13JoinedRoomEventBody\x12&\n" +
	"\tuser_full\x18\x01 \x01(\v2\t.api.UserR\buserFull\"0\n" +
	"\x11LeftRoomEventBody\x12\x1b\n" +
	"\tleft_room\x18\x01 \x01(\bR\bleftRoom\"\xa3\x01\n" +
	"\x13DataEditedEventBody\x12\x17\n" +
	"\adata_id\x18\x01 \x01(\tR\x06dataId\x12.\n" +
	"\n" +
	"data_value\x18\x02 \x01(\v2\n" +
	".api.ValueH\x00R\tdataValue\x88\x01\x01\x124\n" +
	"\fcommand_mode\x18\x03 \x01(\x0e2\x11.api.DateEditModeR\vcommandModeB\r\n" +
	"\v_data_value\"_\n" +
	"\x19FullRoomSnapshotEventBody\x12!\n" +
	"\x04room\x18\x01 \x01(\v2\r.api.RoomDataR\x04room\x12\x1f\n" +
	"\x05users\x18\x02 \x03(\v2\t.api.UserR\x05users\"\x96\x01\n" +
	"\vSingleEvent\x12=\n" +
	"\tfull_room\x18\x01 \x01(\v2\x1e.api.FullRoomSnapshotEventBodyH\x00R\bfullRoom\x12>\n" +
	"\froom_deleted\x18\x02 \x01(\v2\x19.api.RoomDeletedEventBodyH\x00R\vroomDeletedB\b\n" +
	"\x06result*/\n" +
	"\fDateEditMode\x12\a\n" +
	"\x03SET\x10\x00\x12\n" +
	"\n" +
	"\x06DELETE\x10\x01\x12\n" +
	"\n" +
	"\x06APPEND\x10\x022f\n" +
	"\vRoomService\x12&\n" +
	"\x06Stream\x12\f.api.Command\x1a\n" +
	".api.Event(\x010\x01\x12/\n" +
	"\rSingleCommand\x12\f.api.Command\x1a\x10.api.SingleEventB\x16Z\x14pkg/api/room_serviceb\x06proto3"

var (
	file_api_room_service_room_service_proto_rawDescOnce sync.Once
	file_api_room_service_room_service_proto_rawDescData []byte
)

func file_api_room_service_room_service_proto_rawDescGZIP() []byte {
	file_api_room_service_room_service_proto_rawDescOnce.Do(func() {
		file_api_room_service_room_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_room_service_room_service_proto_rawDesc), len(file_api_room_service_room_service_proto_rawDesc)))
	})
	return file_api_room_service_room_service_proto_rawDescData
}

var file_api_room_service_room_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_room_service_room_service_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_api_room_service_room_service_proto_goTypes = []any{
	(DateEditMode)(0),                      // 0: api.DateEditMode
	(*Value)(nil),                          // 1: api.Value
	(*ListValue)(nil),                      // 2: api.ListValue
	(*MapValue)(nil),                       // 3: api.MapValue
	(*User)(nil),                           // 4: api.User
	(*RoomData)(nil),                       // 5: api.RoomData
	(*Command)(nil),                        // 6: api.Command
	(*CreateRoomCommandBody)(nil),          // 7: api.CreateRoomCommandBody
	(*DeleteRoomCommandBody)(nil),          // 8: api.DeleteRoomCommandBody
	(*JoinRoomCommandBody)(nil),            // 9: api.JoinRoomCommandBody
	(*LeaveRoomCommandBody)(nil),           // 10: api.LeaveRoomCommandBody
	(*SetAppendDeleteDataCommandBody)(nil), // 11: api.SetAppendDeleteDataCommandBody
	(*RefreshRoomCommandBody)(nil),         // 12: api.RefreshRoomCommandBody
	(*Event)(nil),                          // 13: api.Event
	(*RoomCreatedEventBody)(nil),           // 14: api.RoomCreatedEventBody
	(*RoomDeletedEventBody)(nil),           // 15: api.RoomDeletedEventBody
	(*JoinedRoomEventBody)(nil),            // 16: api.JoinedRoomEventBody
	(*LeftRoomEventBody)(nil),              // 17: api.LeftRoomEventBody
	(*DataEditedEventBody)(nil),            // 18: api.DataEditedEventBody
	(*FullRoomSnapshotEventBody)(nil),      // 19: api.FullRoomSnapshotEventBody
	(*SingleEvent)(nil),                    // 20: api.SingleEvent
	nil,                                    // 21: api.MapValue.ValuesEntry
	nil,                                    // 22: api.User.MetadataEntry
	nil,                                    // 23: api.RoomData.ValuesEntry
	nil,                                    // 24: api.CreateRoomCommandBody.RoomOptionsEntry
	nil,                                    // 25: api.RoomCreatedEventBody.RoomOptionsEntry
}
var file_api_room_service_room_service_proto_depIdxs = []int32{
	2,  // 0: api.Value.list_value:type_name -> api.ListValue
	3,  // 1: api.Value.map_value:type_name -> api.MapValue
	1,  // 2: api.ListValue.values:type_name -> api.Value
	21, // 3: api.MapValue.values:type_name -> api.MapValue.ValuesEntry
	22, // 4: api.User.metadata:type_name -> api.User.MetadataEntry
	23, // 5: api.RoomData.values:type_name -> api.RoomData.ValuesEntry
	7,  // 6: api.Command.create_room:type_name -> api.CreateRoomCommandBody
	8,  // 7: api.Command.delete_room:type_name -> api.DeleteRoomCommandBody
	9,  // 8: api.Command.join_room:type_name -> api.JoinRoomCommandBody
	10, // 9: api.Command.leave_room:type_name -> api.LeaveRoomCommandBody
	11, // 10: api.Command.affect_data:type_name -> api.SetAppendDeleteDataCommandBody
	12, // 11: api.Command.refresh_room:type_name -> api.RefreshRoomCommandBody
	24, // 12: api.CreateRoomCommandBody.room_options:type_name -> api.CreateRoomCommandBody.RoomOptionsEntry
	4,  // 13: api.JoinRoomCommandBody.user_full:type_name -> api.User
	1,  // 14: api.SetAppendDeleteDataCommandBody.data_value:type_name -> api.Value
	0,  // 15: api.SetAppendDeleteDataCommandBody.command_mode:type_name -> api.DateEditMode
	14, // 16: api.Event.room_created:type_name -> api.RoomCreatedEventBody
	15, // 17: api.Event.room_deleted:type_name -> api.RoomDeletedEventBody
	16, // 18: api.Event.joined_room:type_name -> api.JoinedRoomEventBody
	17, // 19: api.Event.left_room:type_name -> api.LeftRoomEventBody
	18, // 20: api.Event.data_edited:type_name -> api.DataEditedEventBody
	19, // 21: api.Event.full_room:type_name -> api.FullRoomSnapshotEventBody
	25, // 22: api.RoomCreatedEventBody.room_options:type_name -> api.RoomCreatedEventBody.RoomOptionsEntry
	4,  // 23: api.JoinedRoomEventBody.user_full:type_name -> api.User
	1,  // 24: api.DataEditedEventBody.data_value:type_name -> api.Value
	0,  // 25: api.DataEditedEventBody.command_mode:type_name -> api.DateEditMode
	5,  // 26: api.FullRoomSnapshotEventBody.room:type_name -> api.RoomData
	4,  // 27: api.FullRoomSnapshotEventBody.users:type_name -> api.User
	19, // 28: api.SingleEvent.full_room:type_name -> api.FullRoomSnapshotEventBody
	15, // 29: api.SingleEvent.room_deleted:type_name -> api.RoomDeletedEventBody
	1,  // 30: api.MapValue.ValuesEntry.value:type_name -> api.Value
	1,  // 31: api.RoomData.ValuesEntry.value:type_name -> api.Value
	6,  // 32: api.RoomService.Stream:input_type -> api.Command
	6,  // 33: api.RoomService.SingleCommand:input_type -> api.Command
	13, // 34: api.RoomService.Stream:output_type -> api.Event
	20, // 35: api.RoomService.SingleCommand:output_type -> api.SingleEvent
	34, // [34:36] is the sub-list for method output_type
	32, // [32:34] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_api_room_service_room_service_proto_init() }
func file_api_room_service_room_service_proto_init() {
	if File_api_room_service_room_service_proto != nil {
		return
	}
	file_api_room_service_room_service_proto_msgTypes[0].OneofWrappers = []any{
		(*Value_StringValue)(nil),
		(*Value_IntValue)(nil),
		(*Value_FloatValue)(nil),
		(*Value_BoolValue)(nil),
		(*Value_BinaryValue)(nil),
		(*Value_ListValue)(nil),
		(*Value_MapValue)(nil),
	}
	file_api_room_service_room_service_proto_msgTypes[5].OneofWrappers = []any{
		(*Command_CreateRoom)(nil),
		(*Command_DeleteRoom)(nil),
		(*Command_JoinRoom)(nil),
		(*Command_LeaveRoom)(nil),
		(*Command_AffectData)(nil),
		(*Command_RefreshRoom)(nil),
	}
	file_api_room_service_room_service_proto_msgTypes[10].OneofWrappers = []any{}
	file_api_room_service_room_service_proto_msgTypes[12].OneofWrappers = []any{
		(*Event_RoomCreated)(nil),
		(*Event_RoomDeleted)(nil),
		(*Event_JoinedRoom)(nil),
		(*Event_LeftRoom)(nil),
		(*Event_DataEdited)(nil),
		(*Event_FullRoom)(nil),
	}
	file_api_room_service_room_service_proto_msgTypes[17].OneofWrappers = []any{}
	file_api_room_service_room_service_proto_msgTypes[19].OneofWrappers = []any{
		(*SingleEvent_FullRoom)(nil),
		(*SingleEvent_RoomDeleted)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_room_service_room_service_proto_rawDesc), len(file_api_room_service_room_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_room_service_room_service_proto_goTypes,
		DependencyIndexes: file_api_room_service_room_service_proto_depIdxs,
		EnumInfos:         file_api_room_service_room_service_proto_enumTypes,
		MessageInfos:      file_api_room_service_room_service_proto_msgTypes,
	}.Build()
	File_api_room_service_room_service_proto = out.File
	file_api_room_service_room_service_proto_goTypes = nil
	file_api_room_service_room_service_proto_depIdxs = nil
}
